#!/bin/bash
#
# Mat Wrapper
# Runs 'mat' inside a container, this script is intended
# to be used as the 'mat' command
#
# Behind scenes this script will:
# 1. Create a docker container with 'mat'
# 2. Mount current path '$PWD' as a volume in /mat container path
# 3. Invoke 'mat' command inside container by passing arguments
#

# ref: https://stackoverflow.com/a/4774063/3211029
HERE="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
CURR_PATH="${pwd}"
cd "${HERE}"

if [ ! -f .env ]; then
    echo "File '.env' not found"
    exit 1
fi

# Load following variables from .env
# MAT_DOCKER_IMAGE_VERSION
# MAT_DOCKER_NETWORK
source .env

docker run --rm \
  --network "${MAT_DOCKER_NETWORK}" \
  -ti -v "$PWD":/mat \
  giobyte8/mat:"$MAT_DOCKER_IMAGE_VERSION" "$@"
