#!/bin/bash
#
# Mat Wrapper
# Runs 'mat' inside a container, this script is intended
# to be used as the 'mat' command
#
# Behind scenes this script will:
# 1. Create a docker container with 'mat'
# 2. Mount current path '$PWD' as a volume in /mat container path
# 3. Invoke 'mat' command inside container by passing arguments
#

DOCKER_IMAGE_TAG=1.0.2
docker run --rm --network dockerdev_default -ti -v "$PWD":/mat giobyte8/mat:"$DOCKER_IMAGE_TAG" "$@"
